"""
Generates a regulator-grade cutover audit PDF.
Designed to look like a real compliance sign-off document.
"""

from datetime import datetime, timezone
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

# ── Colours ───────────────────────────────────────────────────────────────────
C_DARK = colors.HexColor("#0e1117")
C_BRAND = colors.HexColor("#6366f1")
C_GREEN = colors.HexColor("#00C851")
C_YELLOW = colors.HexColor("#FFBB33")
C_ORANGE = colors.HexColor("#FF8800")
C_RED = colors.HexColor("#FF4444")
C_LIGHT_GREY = colors.HexColor("#f3f4f6")
C_MID_GREY = colors.HexColor("#6b7280")
C_BORDER = colors.HexColor("#e5e7eb")

VERDICT_COLOUR = {
    "SAFE_TO_CUT": C_GREEN,
    "CUT_WITH_MONITORING": C_YELLOW,
    "HOLD_INVESTIGATE": C_ORANGE,
    "DO_NOT_CUT": C_RED,
}

W, H = A4


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Normal"],
                                fontSize=22, leading=28,
                                textColor=C_DARK, fontName="Helvetica-Bold"),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"],
                                   fontSize=11, leading=16,
                                   textColor=C_MID_GREY, fontName="Helvetica"),
        "section": ParagraphStyle("section", parent=base["Normal"],
                                  fontSize=13, leading=18, spaceBefore=14, spaceAfter=4,
                                  textColor=C_BRAND, fontName="Helvetica-Bold"),
        "body": ParagraphStyle("body", parent=base["Normal"],
                               fontSize=9, leading=14,
                               textColor=C_DARK, fontName="Helvetica"),
        "small": ParagraphStyle("small", parent=base["Normal"],
                                fontSize=8, leading=12,
                                textColor=C_MID_GREY, fontName="Helvetica"),
        "bold": ParagraphStyle("bold", parent=base["Normal"],
                               fontSize=9, leading=14,
                               textColor=C_DARK, fontName="Helvetica-Bold"),
        "centre": ParagraphStyle("centre", parent=base["Normal"],
                                 fontSize=9, leading=14, alignment=TA_CENTER,
                                 textColor=C_DARK, fontName="Helvetica"),
    }


def _header_footer(canvas, doc):
    canvas.saveState()
    # Header bar
    canvas.setFillColor(C_BRAND)
    canvas.rect(0, H - 18 * mm, W, 18 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(20 * mm, H - 11 * mm, "BOB THE JUDGE")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(W - 20 * mm, H - 11 * mm, "MIGRATION CUTOVER AUDIT REPORT")
    # Footer
    canvas.setFillColor(C_MID_GREY)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(20 * mm, 10 * mm,
                      "CONFIDENTIAL — For internal migration governance and regulatory review only.")
    canvas.drawRightString(W - 20 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def generate_pdf(scores: list[dict], results: list[dict], run_ts: datetime | None = None) -> bytes:
    if run_ts is None:
        run_ts = datetime.now(timezone.utc)

    buf = BytesIO()
    s = _styles()

    doc = BaseDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=28 * mm,
        bottomMargin=22 * mm,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin,
                  doc.width, doc.height, id="main")
    doc.addPageTemplates([PageTemplate(id="main", frames=frame,
                                       onPage=_header_footer)])

    story = []

    # ── Cover block ────────────────────────────────────────────────────────
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph("Migration Cutover Audit Report", s["title"]))
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(
        f"Generated by Bob the Judge &nbsp;·&nbsp; "
        f"{run_ts.strftime('%d %B %Y, %H:%M UTC')} &nbsp;·&nbsp; "
        f"Banking Payment Processing Domain",
        s["subtitle"],
    ))
    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=C_BORDER))
    story.append(Spacer(1, 4 * mm))

    # ── Executive summary ──────────────────────────────────────────────────
    total_txns = sum(s_["total_transactions"] for s_ in scores)
    overall_parity = (
        sum(s_["parity_rate_pct"] * s_["total_transactions"] for s_ in scores)
        / max(total_txns, 1)
    )
    safe_count = sum(1 for s_ in scores if s_["verdict"] == "SAFE_TO_CUT")
    blocked_count = sum(1 for s_ in scores if s_["verdict"] == "DO_NOT_CUT")

    summary_data = [
        ["Metric", "Value"],
        ["Total Transactions Analysed", f"{total_txns:,}"],
        ["Overall Parity Rate", f"{overall_parity:.1f}%"],
        ["Functions Cleared for Cutover", f"{safe_count} of {len(scores)}"],
        ["Functions Blocked", f"{blocked_count}"],
        ["Analysis Timestamp", run_ts.strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["System Under Test", "Banking Payment Processor (Legacy → Modern)"],
    ]

    story.append(Paragraph("Executive Summary", s["section"]))
    t = Table(summary_data, colWidths=[90 * mm, 75 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), C_BRAND),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_LIGHT_GREY, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, C_BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(t)
    story.append(Spacer(1, 6 * mm))

    # ── Function scorecards ────────────────────────────────────────────────
    story.append(Paragraph("Function-Level Cutover Verdicts", s["section"]))

    header = ["Payment Function", "Transactions", "Parity %", "Score", "Verdict",
              "Avg Fee Diff", "Latency Gain"]
    rows = [header]
    for sc in scores:
        rows.append([
            sc["function"],
            str(sc["total_transactions"]),
            f"{sc['parity_rate_pct']:.1f}%",
            f"{sc['readiness_score']:.1f}",
            sc["verdict"].replace("_", " "),
            f"${sc['avg_fee_diff_usd']:.4f}",
            f"{sc['avg_latency_improvement_pct']:+.1f}%",
        ])

    col_w = [55 * mm, 22 * mm, 18 * mm, 15 * mm, 32 * mm, 22 * mm, 22 * mm]
    t2 = Table(rows, colWidths=col_w)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), C_DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_LIGHT_GREY, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, C_BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
    ]
    for i, sc in enumerate(scores, start=1):
        c = VERDICT_COLOUR.get(sc["verdict"], C_MID_GREY)
        style_cmds.append(("TEXTCOLOR", (4, i), (4, i), c))
        style_cmds.append(("FONTNAME", (4, i), (4, i), "Helvetica-Bold"))
    t2.setStyle(TableStyle(style_cmds))
    story.append(t2)
    story.append(Spacer(1, 6 * mm))

    # ── Divergence detail ──────────────────────────────────────────────────
    divergent = [r for r in results if not r["parity"]]
    story.append(Paragraph(
        f"Divergence Detail ({len(divergent)} divergent transactions)", s["section"]
    ))

    if divergent:
        div_header = ["Transaction ID", "Type", "Amount", "Field", "Legacy", "Modern", "Severity"]
        div_rows = [div_header]
        for r in divergent[:30]:
            for d in r["divergences"]:
                div_rows.append([
                    r["transaction_id"],
                    r["transaction_type"].title(),
                    f"${r['amount']:,.2f} {r['currency']}",
                    d["field"],
                    str(d["legacy"])[:12],
                    str(d["modern"])[:12],
                    d["severity"],
                ])
        if len(divergent) > 30:
            div_rows.append(["…", f"+ {len(divergent) - 30} more", "", "", "", "", ""])

        col_w2 = [30 * mm, 22 * mm, 28 * mm, 25 * mm, 20 * mm, 20 * mm, 20 * mm]
        t3 = Table(div_rows, colWidths=col_w2)
        sev_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e2130")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_LIGHT_GREY, colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.4, C_BORDER),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]
        for i, r in enumerate(divergent[:30], start=1):
            for d in r["divergences"]:
                sev = d["severity"]
                c = {"CRITICAL": C_RED, "HIGH": C_ORANGE, "MEDIUM": C_YELLOW}.get(sev, C_MID_GREY)
                sev_style.append(("TEXTCOLOR", (6, i), (6, i), c))
                sev_style.append(("FONTNAME", (6, i), (6, i), "Helvetica-Bold"))
        t3.setStyle(TableStyle(sev_style))
        story.append(t3)
    else:
        story.append(Paragraph("No divergences detected. All functions at 100% parity.", s["body"]))

    story.append(Spacer(1, 6 * mm))

    # ── Recommendations ────────────────────────────────────────────────────
    story.append(Paragraph("Bob the Judge — Cutover Recommendation", s["section"]))

    for sc in scores:
        verdict = sc["verdict"]
        colour = VERDICT_COLOUR.get(verdict, C_MID_GREY)
        label = verdict.replace("_", " ")

        if verdict == "SAFE_TO_CUT":
            action = (
                f"<b>{sc['function']}</b> has achieved {sc['parity_rate_pct']:.1f}% parity "
                f"across {sc['total_transactions']} transactions with a readiness score of "
                f"{sc['readiness_score']:.1f}/100. <b>Approved for immediate cutover.</b> "
                f"No further parallel run required."
            )
        elif verdict == "CUT_WITH_MONITORING":
            action = (
                f"<b>{sc['function']}</b> shows {sc['parity_rate_pct']:.1f}% parity "
                f"(score {sc['readiness_score']:.1f}/100). Cutover is permitted with "
                f"real-time monitoring. Recommend 24-hour observation window post-cutover."
            )
        elif verdict == "HOLD_INVESTIGATE":
            action = (
                f"<b>{sc['function']}</b> at {sc['parity_rate_pct']:.1f}% parity "
                f"(score {sc['readiness_score']:.1f}/100). Divergences require investigation "
                f"before cutover. Extend parallel run by minimum 7 days."
            )
        else:
            action = (
                f"<b>{sc['function']}</b> at {sc['parity_rate_pct']:.1f}% parity "
                f"(score {sc['readiness_score']:.1f}/100). <b>Cutover blocked.</b> "
                f"Critical divergences detected — escalate to migration lead and compliance team."
            )

        rec_data = [[f"  {label}", Paragraph(action, s["body"])]]
        t_rec = Table(rec_data, colWidths=[38 * mm, 130 * mm])
        t_rec.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, 0), colour),
            ("TEXTCOLOR", (0, 0), (0, 0), colors.white),
            ("FONTNAME", (0, 0), (0, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (0, 0), 8),
            ("ALIGN", (0, 0), (0, 0), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BACKGROUND", (1, 0), (1, 0), colors.white),
            ("BOX", (0, 0), (-1, -1), 0.5, C_BORDER),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(KeepTogether([t_rec, Spacer(1, 3 * mm)]))

    # ── Sign-off block ─────────────────────────────────────────────────────
    story.append(Spacer(1, 8 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=C_BORDER))
    story.append(Spacer(1, 4 * mm))

    signoff_data = [
        ["Migration Lead", "Compliance Officer", "CTO Sign-off"],
        ["", "", ""],
        ["Signature: _______________", "Signature: _______________", "Signature: _______________"],
        ["Date: _______________", "Date: _______________", "Date: _______________"],
    ]
    t_sign = Table(signoff_data, colWidths=[55 * mm, 55 * mm, 55 * mm])
    t_sign.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (0, 0), (-1, 0), C_DARK),
        ("TEXTCOLOR", (0, 2), (-1, -1), C_MID_GREY),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEABOVE", (0, 0), (-1, 0), 0.5, C_BRAND),
    ]))
    story.append(t_sign)

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        "This report was generated automatically by Bob the Judge, an IBM Bob-powered migration "
        "cutover decision system. It constitutes a machine-generated audit artefact and must be "
        "countersigned by authorised personnel before use in regulatory submissions.",
        s["small"],
    ))

    doc.build(story)
    return buf.getvalue()
